### ISSUE TITLE
[SampleAndHoldSim] Version 0.5.0, when the game is restarted and the save is loaded, there will be intermittent stuttering

### ISSUE THREAD

**Issue by blacksnownight** [starfi5h/DSP_Mod#13]
![QQ图片20230326213636](https://user-images.githubusercontent.com/128919146/227779653-a54be2b1-dcb4-4f1d-a10d-874a065a3a5c.png)
https://youtu.be/5dS6l6sdI6o
As the title says, when entering the game for the first time, the game will continue to stutter (as shown in the picture above), and it will not be relieved until the first automatic save or manual save.
The milliseconds of lag depends on whether Icarus is moving. For example, the milliseconds of lag will be higher when he keeps moving (200~500ms)

**Comment by starfi5h** [comment]
Hmm.. This seems weird.
Are there other mods? Does this happen only when SampleAndHoldSim is installed?
If UPS can handle, consider using AlterTickrate instead. May it is more stable.

**Comment by blacksnownight** [comment]
![QQ图片20230327021120](https://user-images.githubusercontent.com/128919146/227795554-fbcab920-10f0-4f03-80b4-f543d34e99ac.png)
There is also DSPOptimizations, and there are no other mods

**Comment by starfi5h** [comment]
Since the stuttering happened in different parts, it may due to system garbage collection.
I try to reduce memory allocation of the mod in version 0.5.1.
The stuttering solves after game save is weird because the mod doesn't modify stuff with saving process.
If the stutter still occurs, try to seek mods that help game save, for example [BulletTime](https://dsp.thunderstore.io/package/starfi5h/BulletTime/), [CompressSave](https://dsp.thunderstore.io/package/soarqin/CompressSave/), [LossyCompression](https://dsp.thunderstore.io/package/starfi5h/LossyCompression/)

**Comment by blacksnownight** [comment]
It has been updated to version 0.5.1. After entering the game for the first time, there will only be about 3 stuttering times and then it will stop stuttering. Thank you.
